//common js , every file is module (by default)
// Modules - encapsulated code (only share minimum)
const names = require('./names')
const sayHi = require('./5-util')
const data = require('./6-alt')
require('./7-mind')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)